from __future__ import annotations

"""Documentation generator for NovaDev 1.0 projects."""

from pathlib import Path
from typing import List

from .ast_nodes import Program


class DocumentationGenerator:
    def generate(self, program: Program, output_dir: Path | str) -> List[Path]:
        output = Path(output_dir)
        output.mkdir(parents=True, exist_ok=True)
        app = program.app
        target = output / "novadev-summary.md"
        if app:
            content = f"""# {app.name}

Generated by NovaDev 1.0.

- Tables: {len(app.tables)}
- Pages: {len(app.pages)}
- Routes: {len(app.routes)}
- Plugins: {len(app.plugins)}
- Discoveries: {len(app.discoveries)}
"""
        else:
            content = "# NovaDev Program\n\nNo app declaration was found.\n"
        target.write_text(content, encoding="utf-8")
        return [target]
