from __future__ import annotations

"""Frontend project generator for NovaDev 0.4.

This file wraps the beginner-friendly `UIGenerator` and arranges its output into
a project-style frontend folder: `index.html`, `css/style.css`, and `js/app.js`.
It also creates simple page entry files so generated apps feel closer to a real
multi-page web project.
"""

from pathlib import Path
from typing import List

from .ast_nodes import Program
from .runtime import Runtime
from .ui_generator import UIGenerator


class FrontendGenerator:
    def generate(self, program: Program, output_dir: Path | str) -> List[Path]:
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        generated = list(UIGenerator().generate(program, output_path))
        moved = self.organize_assets(output_path)
        page_files = self.write_page_entry_files(program, output_path)
        readme = output_path / "README.md"
        readme.write_text(self.readme(), encoding="utf-8")

        return [*moved, *page_files, readme]

    def organize_assets(self, output_path: Path) -> List[Path]:
        css_dir = output_path / "css"
        js_dir = output_path / "js"
        css_dir.mkdir(exist_ok=True)
        js_dir.mkdir(exist_ok=True)

        moved: List[Path] = []
        style_source = output_path / "style.css"
        style_target = css_dir / "style.css"
        if style_source.exists():
            style_source.replace(style_target)
            moved.append(style_target)

        js_source = output_path / "app.js"
        js_target = js_dir / "app.js"
        if js_source.exists():
            js_source.replace(js_target)
            moved.append(js_target)

        index_path = output_path / "index.html"
        if index_path.exists():
            html = index_path.read_text(encoding="utf-8")
            html = html.replace('href="style.css"', 'href="css/style.css"')
            html = html.replace('src="app.js"', 'src="js/app.js"')
            index_path.write_text(html, encoding="utf-8")
            moved.insert(0, index_path)

        return moved

    def write_page_entry_files(self, program: Program, output_path: Path) -> List[Path]:
        runtime = Runtime()
        runtime.load_declarations(program)
        files: List[Path] = []

        for page in runtime.pages:
            filename = self.page_filename(page.route_path)
            if filename == "index.html":
                continue
            path = output_path / filename
            path.write_text(self.page_redirect_html(page.display_title(), page.route_path), encoding="utf-8")
            files.append(path)

        return files

    def page_filename(self, route_path: str) -> str:
        clean = route_path.strip("/").replace("/", "-") or "index"
        return f"{clean}.html"

    def page_redirect_html(self, title: str, route_path: str) -> str:
        target = f"index.html#{route_path}"
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <meta http-equiv="refresh" content="0; url={target}">
    <script>location.replace({target!r});</script>
</head>
<body>
    <a href="{target}">Open {title}</a>
</body>
</html>
"""

    def readme(self) -> str:
        return """# NovaDev Frontend

This folder was generated by NovaDev 0.4.

- `index.html` is the main browser app.
- `css/style.css` contains the generated styling.
- `js/app.js` contains the generated browser behavior and API calls.

Open the project through the generated Flask backend so API calls work.
"""
